#! /bin/sh

. ${curdir}/${predir}funcutil

fn_agentuipreinst() {
    if [ ! -f ${td_start_theme_file} ] ; then
        echo "${td_start_theme_file} not found." >> ${td_log_dir}/${td_log_file} 2>&1
        return
    fi

    singleitem="\'${td_extension_dir}\'"
    appenditem=", \'${td_extension_dir}\'"
    appenditem2=",\'${td_extension_dir}\'"
    isnotempty=`cat ${td_start_theme_file} | sed -e "s/${appenditem}//g" | sed -e "s/${appenditem2}//g" | sed -e "s/${singleitem}//g" | grep "enabled-extensions\ \"\[" | sed -e "s/\(gsettings\ set\ org.gnome.shell\ enabled-extensions\ \"\[\)\(.*\)\(\]\"\)/\2/g" | sed -e "s/ //g"`

    if [ "x${isnotempty}" = "x" ] ; then
        _additem=${singleitem}
    else
        _additem=${appenditem}
    fi

    if [ ! -f ${td_start_theme_file}.bak ] ; then
        cp ${td_start_theme_file} ${td_start_theme_file}.bak >> ${td_log_dir}/${td_log_file} 2>&1
    fi
    cat ${td_start_theme_file} | sed -e "s/${appenditem}//g" | sed -e "s/${appenditem2}//g" | sed -e "s/${singleitem}//g" | sed -e "s/\(enabled-extensions\ \"\[\)\(.*\)\(\]\"\)/\1\2${_additem}\3/g" > ${td_start_theme_file}.1 2>> ${td_log_dir}/${td_log_file}
    mv ${td_start_theme_file}.1 ${td_start_theme_file} >> ${td_log_dir}/${td_log_file} 2>&1
}

fn_agentuiinst() {
    if [ -f ${td_service_root}/${td_desktop_file} ] ; then

        # root user
        mkdir -p ${td_roothome_dir}/${td_startup_dir} >> ${td_log_dir}/${td_log_file} 2>&1
        rm -f ${td_roothome_dir}/${td_startup_dir}/${td_desktop_file} >> ${td_log_dir}/${td_log_file} 2>&1
        ln -s ${td_service_root}/${td_desktop_file} ${td_roothome_dir}/${td_startup_dir}/${td_desktop_file} >> ${td_log_dir}/${td_log_file} 2>&1

        # normal users
        for account in `LANG=C grep "/bin/bash" /etc/passwd | awk -F: '{print $1}'`
        do
            home_folder=$(eval echo ~${account})

            su -c "mkdir -p ${home_folder}/${td_startup_dir}" ${account} >> ${td_log_dir}/${td_log_file} 2>&1
            rm -f ${home_folder}/${td_startup_dir}/${td_desktop_file} >> ${td_log_dir}/${td_log_file} 2>&1
            su -c "ln -s ${td_service_root}/${td_desktop_file} ${home_folder}/${td_startup_dir}/${td_desktop_file}" ${account} >> ${td_log_dir}/${td_log_file} 2>&1
            chmod 777 -R ${home_folder}/${td_startup_dir} >> ${td_log_dir}/${td_log_file} 2>&1

            su -c "mkdir -p ${home_folder}/${td_extension_base}" ${account} >> ${td_log_dir}/${td_log_file} 2>&1
            rm -fr ${home_folder}/${td_extension_base}/${td_extension_dir} >> ${td_log_dir}/${td_log_file} 2>&1
            su -c "cp -fr ${td_service_root}/extensions/${td_extension_dir} ${home_folder}/${td_extension_base}" ${account} >> ${td_log_dir}/${td_log_file} 2>&1
            chmod 777 -R ${home_folder}/${td_extension_base} >> ${td_log_dir}/${td_log_file} 2>&1

            chown ${account} -R ${home_folder} >> ${td_log_dir}/${td_log_file} 2>&1

            # Get gnome-shell version
            gnome_shell_version=`gnome-shell --version | grep -o '3.*.*'`
            extension_metadata_file=metadata.json
            str=`cat ${home_folder}/${td_extension_base}/${td_extension_dir}/${extension_metadata_file}`
            result=`echo $str | grep ${gnome_shell_version}`
            if [ "$result" = "" ] ; then
                pattern="s/\]/,\"${gnome_shell_version}\"\]/g"
                sed -i $pattern ${home_folder}/${td_extension_base}/${td_extension_dir}/${extension_metadata_file} >> ${td_log_dir}/${td_log_file} 2>&1
                sync
            fi
            
            # Register extension
            _list_m=`su -c "gsettings get org.gnome.shell enabled-extensions 2>&1" ${account} | cut -d'[' -f 2 | cut -d']' -f 1 | sed "s/'${td_extension_dir}', //" | sed "s/'${td_extension_dir}'//"`
            _list_l=`su -c "gsettings get org.gnome.shell enabled-extensions 2>&1" ${account} | cut -d'[' -f 1`
            _list_r=`su -c "gsettings get org.gnome.shell enabled-extensions 2>&1" ${account} | cut -d']' -f 2`
            if [ "x${_oldlist}" = "x" ] ; then
                _newlist="${_list_l}['${td_extension_dir}']${_list_r}"
            else
                _newlist="${_list_l}[${_list_m}, '${td_extension_dir}']${_list_r}"
            fi
            echo "su -c \"gsettings set org.gnome.shell enabled-extensions \"${_newlist}\"\" ${account}" >> ${td_log_dir}/${td_log_file} 2>&1
            nohup su -c "gsettings set org.gnome.shell enabled-extensions \"${_newlist}\"" ${account} >> ${td_log_dir}/${td_log_file} 2>&1 &
        done
    fi

    # Permission settings
    mkdir -p ${td_agentui_syslog} >> ${td_log_dir}/${td_log_file} 2>&1
    chmod 777 -R ${td_agentui_syslog} >> ${td_log_dir}/${td_log_file} 2>&1
    [ -f ${td_service_root}/${td_agentui_file} ] && chmod 755 ${td_service_root}/${td_agentui_file} >> ${td_log_dir}/${td_log_file} 2>&1
    [ -f ${td_service_root}/${td_agentui_runfile} ] && chmod 755 ${td_service_root}/${td_agentui_runfile} >> ${td_log_dir}/${td_log_file} 2>&1
    [ -f ${td_service_root}/${td_agentui_autorunfile} ] && chmod 755 ${td_service_root}/${td_agentui_autorunfile} >> ${td_log_dir}/${td_log_file} 2>&1
    # locale-gen >> ${td_log_dir}/${td_log_file} 2>&1

    [ -f ${td_lang_file} ] && chmod 777 ${td_lang_file} >> ${td_log_dir}/${td_log_file} 2>&1
}

fn_agentuiremove() {
    # root user
    rm -f ${td_roothome_dir}/${td_startup_dir}/${td_desktop_file} >> ${td_log_dir}/${td_log_file} 2>&1

    # normal users
    for account in `LANG=C grep "/bin/bash" /etc/passwd | awk -F: '{print $1}'`
    do
        home_folder=$(eval echo ~${account})

        rm -f ${home_folder}/${td_startup_dir}/${td_desktop_file} >> ${td_log_dir}/${td_log_file} 2>&1
        rm -fr ${home_folder}/${td_extension_base}/${td_extension_dir} >> ${td_log_dir}/${td_log_file} 2>&1

        # Unregister extension
        _list_m=`su -c "gsettings get org.gnome.shell enabled-extensions 2>&1" ${account} | cut -d'[' -f 2 | cut -d']' -f 1 | sed "s/'${td_extension_dir}', //" | sed "s/'${td_extension_dir}'//"`
        _list_l=`su -c "gsettings get org.gnome.shell enabled-extensions 2>&1" ${account} | cut -d'[' -f 1`
        _list_r=`su -c "gsettings get org.gnome.shell enabled-extensions 2>&1" ${account} | cut -d']' -f 2`
        if [ "x${_oldlist}" = "x" ] ; then
            _newlist="${_list_l}[]${_list_r}"
        else
            _newlist="${_list_l}[${_list_m}]${_list_r}"
        fi
        echo "su -c \"gsettings set org.gnome.shell enabled-extensions \"${_newlist}\"\" ${account}" >> ${td_log_dir}/${td_log_file} 2>&1
        su -c "gsettings set org.gnome.shell enabled-extensions \"${_newlist}\"" ${account} >> ${td_log_dir}/${td_log_file} 2>&1 &
    done
}

fn_agentuistop() {
    agentuiid=`LANG=C ps -ef | grep "${td_service_root}/${td_agentui_file}" | grep -v grep | tr -s ' ' | awk -F' ' '{print $2}' | head -1`
    if [ "${agentuiid}" != "" ] ; then
        kill ${agentuiid} >> ${td_log_dir}/${td_log_file} 2>&1 &
        fn_agentuikill
    fi
    fn_agenticonstop
}

fn_agentuikill() {
    sleep 5
    agentuiid=`LANG=C ps -ef | grep "${td_service_root}/${td_agentui_file}" | grep -v grep | tr -s ' ' | awk -F' ' '{print $2}' | head -1`
    if [ "${agentuiid}" != "" ] ; then
        kill -9 ${agentuiid} >> ${td_log_dir}/${td_log_file} 2>&1 &
        fn_agentuikill
    fi
    fn_agentuicleanup
}

fn_agenticonstop() {
    agenticonid=`LANG=C ps -ef | grep "${td_agenticon_file}" | grep -v grep | tr -s ' ' | awk -F' ' '{print $2}' | head -1`
    if [ "${agenticonid}" != "" ] ; then
        kill ${agenticonid} >> ${td_log_dir}/${td_log_file} 2>&1 &
        fn_agenticonkill
    fi
}

fn_agenticonkill() {
    sleep 5
    agenticonid=`LANG=C ps -ef | grep "${td_agenticon_file}" | grep -v grep | tr -s ' ' | awk -F' ' '{print $2}' | head -1`
    if [ "${agenticonid}" != "" ] ; then
        kill -9 ${agenticonid} >> ${td_log_dir}/${td_log_file} 2>&1 &
        fn_agenticonkill
    fi
}

fn_agentuistart() {
    LC_ALL=C LANG=C nohup ${td_service_root}/${td_service_file} -r ${td_service_root}/${td_agentui_autorunfile} >> ${td_log_dir}/${td_log_running} 2>&1 &
}

fn_agentuicleanup() {
    rm -fr /tmp/_MEI* > /dev/null
}