#!/bin/sh

trap 'exit 1' 1 2 15

export curdir="/usr/share/theftdeterrentclient"
export predir=""

. ${curdir}/${predir}funcdefine

fn_define

. ${curdir}/${predir}funcutil

fn_syssetlang
fn_syscreatelogdir
fn_syscreateinstdir
fn_sysExitTrap

echo "Install ..." >> ${td_log_dir}/${td_log_file}

. ${curdir}/${predir}funcdefine

fn_define

. ${curdir}/${predir}funcutil

fn_sysExitTrap

. ${curdir}/${predir}funcreturn

fn_sysinst

. ${curdir}/${predir}funcagent

fn_agentstart

# check os
fn_sysCheckosname
. ${curdir}/${predir}funcagentui
[ -f ${curdir}/${predir}funcagentui_${distosname} ] && . ${curdir}/${predir}funcagentui_${distosname}
[ -f ${curdir}/${predir}funcagentui_${fullosname} ] && . ${curdir}/${predir}funcagentui_${fullosname}

fn_agentuistart
fn_agentuipreinst

echo "Install Done." >> ${td_log_dir}/${td_log_file}

fn_agentrebootreq

echo "Generating symlinks to services in /usr/local"
ln -s /opt/TheftDeterrentclient/local/theftdeterrentclient /usr/local/theftdeterrentclient

fn_returncode 0

